---
version: '3.7'

networks:
  chatterbotsnet:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1

services:

  chatterbots-backend:
    image: chatterbots-backend:latest
    container_name: chatterbots-backend
    restart: unless-stopped
    networks:
      - chatterbotsnet
    ports:
      - 7009:7009
    volumes:
      - ./localdev/data:/data

  chatterbots-frontend:
    image: chatterbots-frontend:latest
    container_name: chatterbots-frontend
    restart: unless-stopped
    volumes:
      - ./localdev/avatars:/usr/share/nginx/html/avatars
    networks:
      - chatterbotsnet
    ports:
      - 7003:80
